# theme: jekyll-theme-leap-day

# Site settings
title: CS286
email: hellerstein@berkeley.edu
repository: jhellerstein/cs286-sp24
author:
description: Berkeley Grad Database Course Website Sp24

mermaid: true

# baseurl: /CS286-Sp24

# Build settings
# permalink: :title/
sass:
  sass_dir: css

